using Nancy.TinyIoc;

namespace ei8.Extensions.DependencyInjection.Coding.d23.neurULization
{
    public static class TinyIoCContainerExtensions
    {
        public static void AddReaders(this TinyIoCContainer container)
        {
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IAggregateParser,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.AggregateParser
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.ExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IInstantiatesClassReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.InstantiatesClassReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyValueAssignmentReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyValueAssignmentReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyInstanceValueAssignmentReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyInstanceValueAssignmentReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyValueAssociationReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyValueAssociationReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyInstanceValueAssociationReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyInstanceValueAssociationReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IPropertyInstanceValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.PropertyInstanceValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IUnitReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.UnitReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IValueReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.ValueReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IInstanceValueReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.InstanceValueReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.ValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IInstanceValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.InstanceValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.IInstanceReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Inductive.InstanceReader
            >();

            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.ExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IIdExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IdExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IInstantiatesClassReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.InstantiatesClassReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyValueAssignmentReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyValueAssignmentReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyInstanceValueAssignmentReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyInstanceValueAssignmentReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyValueAssociationReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyValueAssociationReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyInstanceValueAssociationReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyInstanceValueAssociationReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IPropertyInstanceValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.PropertyInstanceValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IUnitReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.UnitReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IValueReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.ValueReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IInstanceValueReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.InstanceValueReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IIdInstanceValueReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IdInstanceValueReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.ValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IInstanceValueExpressionReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.InstanceValueExpressionReader
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.IInstanceReader,
                Cortex.Coding.d23.neurULization.Processors.Readers.Deductive.InstanceReader
            >();
        }

        public static void AddWriters(this TinyIoCContainer container)
        {
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.ExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IIdExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.IdExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IInstantiatesClassWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.InstantiatesClassWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyValueAssignmentWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyValueAssignmentWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyInstanceValueAssignmentWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyInstanceValueAssignmentWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyValueAssociationWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyValueAssociationWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyInstanceValueAssociationWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyInstanceValueAssociationWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyValueExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyValueExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IPropertyInstanceValueExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.PropertyInstanceValueExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IUnitWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.UnitWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IValueWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.ValueWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IInstanceValueWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.InstanceValueWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IIdInstanceValueWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.IdInstanceValueWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IValueExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.ValueExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IInstanceValueExpressionWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.InstanceValueExpressionWriter
            >();
            container.Register<
                Cortex.Coding.d23.neurULization.Processors.Writers.IInstanceWriter,
                Cortex.Coding.d23.neurULization.Processors.Writers.InstanceWriter
            >();
        }
    }
}
